# This file was generated by FitSNAP.
# Hash: 7d0f18e5f22c5c16de11bee161555ab2

pair_style hybrid/overlay zbl 4.0 4.2 snap
pair_coeff 1 1 zbl 73 73
pair_coeff 1 2 zbl 73 6
pair_coeff 2 2 zbl 6 6
pair_coeff * * snap ../TaC_pot.snapcoeff ../TaC_pot.snapparam Ta C