# This file was generated by FitSNAP.
# Hash: 7450ca232a58e8d0a5622b0a9f990e1c

pair_style hybrid/overlay zbl 4.0 4.2 pace product
pair_coeff 1 1 zbl 73 73
pair_coeff 1 2 zbl 73 6
pair_coeff 2 2 zbl 6 6
pair_coeff * * pace ../TaC_pot.yace Ta C

# Setup neighbor style
neighbor 1.0 nsq
neigh_modify once no every 1 delay 0 check yes

# Setup minimization style
min_style	     cg
min_modify	     dmax ${dmax} line quadratic

# Setup output
thermo		1
thermo_style custom step temp pe press pxx pyy pzz pxy pxz pyz lx ly lz vol
thermo_modify norm no
